<a href="https://colab.research.google.com/github/arfankv/pythontasks/blob/main/Day16_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How do you create a NumPy array?

In [ ]:
import numpy as np
num1=np.array([1,2,3,4,5])
print(num1)

[1 2 3 4 5]


How do you access elements in a NumPy array

In [ ]:
num2 = np.array([[67,63,],[34,65]])
print(num2[0,1])

63


How do you perform element-wise operations in NumPy?

In [ ]:
a = np.array([3,4,5,6])
b = np.array([2,9,7,0])
c=a+b
print(c)

[ 5 13 12  6]


How do you reshape a NumPy array?

In [ ]:
list = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
d = list.reshape([2,2,4])
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


How do you find the maximum and minimum values in a NumPy array?

In [ ]:
maxmin = np.array([26,11,23,54,34,100,87])
max_elmt = np.max(maxmin)
min_elmt = np.min(maxmin)
print(max_elmt)
print(min_elmt)

100
11


How do you perform matrix multiplication in NumPy?

In [ ]:
l1 = ([[3 , 4],
       [7 , 8]])

l2 = ([[9 ,10],
      [15, 16]])
result = np.multiply(l1,l2)
print(result)

[[ 27  40]
 [105 128]]



How do you find the mean, median, and standard deviation of a NumPy array?

In [ ]:
mnlst = np.arange(11)
print(mnlst)
avg = np.average(mnlst)
print(" Mean : " ,avg)

[ 0  1  2  3  4  5  6  7  8  9 10]
 Mean :  5.0


In [ ]:
md = np.median(mnlst)
print("Median : ",md)

Median :  5.0


In [ ]:
std = np.sqrt(np.mean((mnlst - np.mean(mnlst)) ** 2))
print("std : ", std)

std :  3.1622776601683795


How do you generate random numbers in a NumPy array?

In [ ]:
rm = np.random.randint(150)
print(rm)

145


How do you find the index of the maximum or minimum value in a NumPy array?

In [ ]:
mxmn = np.array([1, 3, 2, 4, 5, 6, 7])
max_index = np.argmax(mxmn)
min_index = np.argmin(mxmn)

print(f"Index of maximum : {max_index}")
print(f"Index of minimum : {min_index}")

Index of maximum : 6
Index of minimum : 0


How do you concatenate two NumPy arrays

In [ ]:
x = ([[32 , 44],[51,16]])
y = ([[91 ,10],[16,11]])
z = np.concatenate([x, y])
print(z)

[[32 44]
 [51 16]
 [91 10]
 [16 11]]


How do you sort a NumPy array

In [ ]:
f = np.array([[1 , 6],
              [7 , 1]])
k = np.sort(f)
print(k)

[[1 6]
 [1 7]]


How do you find unique elements in a NumPy array

In [ ]:
uq = np.array([1, 3, 2, 4, 6, 5, 7])
qn = np.unique(uq)
print(qn)

[1 2 3 4 5 6 7]


How do you perform element-wise comparison in NumPy?

In [ ]:
h = np.array([2, 4, 6, 7])
g = np.array([2, 6, 6, 8])
h == g

array([ True, False,  True, False])


How do you find the indices of non-zero elements in a NumPy array?

In [ ]:
zro = np.array([0, 3, 0, 4, 6, 0, 7])
ro = np.nonzero(zro)
print(ro)

(array([1, 3, 4, 6]),)


How do you perform element-wise logical operations in NumPy?

In [ ]:
a = np.array([2, 2, 3, 4])
b = np.array([1, 4, 2, 7])

d = np.logical_and(a > 1, b < 3)
print(d)

[ True False  True False]


How do you find the diagonal elements of a NumPy array?

In [ ]:
a = np.array([2, 2, 3, 4])
b = np.array([1, 4, 2, 7])

d = np.logical_and(a > 1, b < 3)
print(d)