<a href="https://colab.research.google.com/github/arfankv/pythontasks/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

How can I slice a 1-dimensional array in NumPy?

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array[1:3])

[2 3]


Can I slice a 2-dimensional array in NumPy?

In [ ]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
print(array1[0:2,1:3])

[[2 3]
 [6 7]]


How can I slice an array with a step in NumPy?

In [ ]:
array3=np.array([1,2,3,4,5])
print(array3[1:4:2])

[2 4]


  Can I use negative indices for slicing in NumPy?

In [ ]:
array2=np.array([1,2,3,4,5,6,])
print(array2[-3:-1])

[4 5]


What happens if I omit the start or end index in a slice?

In [ ]:
array4=np.array([1,2,3,4,5,6])
print(array4[:3])

[1 2 3]


In [ ]:
print(array4[0:])

[1 2 3 4 5 6]


Can I modify the original array using slicing in NumPy?

In [ ]:
array5=np.array([1,2,3,4,5])
array5[:1]=0
print(array5)

[0 2 3 4 5]


How can I slice a multi-dimensional array along a specific axis in NumPy?

In [ ]:

np. take_along_axis(1,1:2,axis=0)